import { DISTRIBUTION_COLUMNS_DISPLAY } from '@/modules/distribution/enum';

export const defaultVisibleColumnsDistribution = [
    DISTRIBUTION_COLUMNS_DISPLAY.THUMBNAIL,
    DISTRIBUTION_COLUMNS_DISPLAY.TITLE,
    DISTRIBUTION_COLUMNS_DISPLAY.ARTIST,
    DISTRIBUTION_COLUMNS_DISPLAY.RELEASE_ID,
    DISTRIBUTION_COLUMNS_DISPLAY.TYPE,
    DISTRIBUTION_COLUMNS_DISPLAY.PUBLISHER,
    DISTRIBUTION_COLUMNS_DISPLAY.UPC,
    DISTRIBUTION_COLUMNS_DISPLAY.STATUS,
    DISTRIBUTION_COLUMNS_DISPLAY.TRACK_COUNT,
    DISTRIBUTION_COLUMNS_DISPLAY.DURATION,
    DISTRIBUTION_COLUMNS_DISPLAY.RELEASE_DATE,
    DISTRIBUTION_COLUMNS_DISPLAY.CREATION_DATE,
    DISTRIBUTION_COLUMNS_DISPLAY.ACTIONS,
];
