export enum APP_ROUTES {
    FORBIDDEN = '/forbidden',
    LOGOUT = '/api/auth/logout',
    NOT_FOUND = '/404',
    SERVER_ERROR = '/500',
    LOG = '/log',
    BATCH_IMPORT = '/batch-import',
    UPLOAD = '/upload',
    PERMISSION = '/permission',
    USER = '/users',
    GRANT_PERMISSION = '/grant-permission',
    HOME = '/',
    DASHBOARD = '/dashboard',
    RELEASES = '/releases',
    RELEASES_CREATE = '/releases/create',
    RELEASES_DETAIL = '/releases/*',
    RELEASE_TYPE = '/release-type',
    TRACKS = '/tracks',
    TRACK_DETAIL = '/tracks/*',
    CREATE_RELEASE = '/release-detail',
    LABELS = '/labels',
    LABEL_DETAIL = '/labels/*',
    ARTISTS = '/artists',
    ARTIST_DETAIL = '/artists/*',
    DISTRIBUTION = '/distribution',
    CHANNELS = '/channels',
    LANGUAGES = '/languages',
    COUNTRIES = '/countries',
    GENRES = '/genres',
    DSP = '/dsp',
    DSP_REPORT = '/dsp-report',
    RELEASE_VIDEOS = '/release-videos',
    RELEASE_VIDEOS_CREATE = '/release-videos/create',
    RELEASE_VIDEOS_DETAIL = '/release-videos/*',
    DSP_TENANT = '/dsp-tenant',
    ARTIST_ROLE = '/artist-role',
    EMAIL_SENDER = '/email-sender',
    TIMEZONE = '/timezone',
    TRACK_TYPE = '/track-types',
    TRACK_ORIGIN_TYPE = '/track-origin-types',
    TRACK_SENSITIVE = '/track-sensitive',
    TENANT = '/tenants',
    TENANT_DETAIL = '/tenants/*',
    TENANT_TIERS = '/tenant-tiers',
    TENANT_ISSUE = '/tenant-issue',
    SETTING = '/setting',
    SIGN_IN = '/sign-in',
    FORGOT_PASSWORD = '/forgot-password',
    RESET_PASSWORD = '/reset-password',
    ROLES = '/roles',
    ACTIONS = '/actions',
    CURRENCIES = '/currencies',
    PRICE_TIERS = '/price-tiers',
    ANALYTICS = '/analytics',
    ANALYTICS_TRACKS = '/analytics/tracks',
    ANALYTICS_RELEASES = '/analytics/releases',
    ANALYTICS_ARTISTS = '/analytics/artists',
    ANALYTICS_LABELS = '/analytics/labels',
    ANALYTICS_TENANTS = '/analytics/tenants',
    ANALYTICS_DSPS = '/analytics/dsps',
    ANALYTICS_DETAIL = '/analytics/*',
    ISSUE_LEVEL = '/issue-level',
    ISSUES = '/issues',
    REVENUE = '/revenue',
    NEWS_CATEGORY = '/news-category',
    NEWS = '/news',
    NEWS_DETAIL = '/news/*',
    AGGREGATOR = '/aggregator',
    REPORT_IMPORT = '/report-import',
    DEAL_TYPE = '/deal-type',
    PING = '/ping',
    RELEASE_LOG = '/release-log',
    RELEASE_EXECUTIONS = '/release-executions',
    RELEASE_SUBMITS = '/release-submits',
    DISTRIBUTION_JOBS = '/distribution-jobs',
    LANDING_NEWS_DETAIL = '/landing/news/*',
    LANDING = '/landing',
}

export const AUTH_ROUTES: string[] = [APP_ROUTES.SIGN_IN];

export const DEFAULT_ROUTE = APP_ROUTES.RELEASES;

export const HOME_ROUTE = APP_ROUTES.DASHBOARD;

export const PUBLIC_ROUTES = [
    APP_ROUTES.NOT_FOUND,
    APP_ROUTES.SERVER_ERROR,
    APP_ROUTES.LANDING,
    APP_ROUTES.LANDING_NEWS_DETAIL,
    APP_ROUTES.HOME,
];

export enum PATH_PARAMS {
    ACTION = 'action',
    RELEASE_ID = 'release-id',
}
