export enum APP_ROUTES {
    FORBIDDEN = '/forbidden',
    LOGOUT = '/api/auth/logout',
    NOT_FOUND = '/404',
    SERVER_ERROR = '/500',
    LOG = '/log',
    BATCH_IMPORT = '/batch-import',
    UPLOAD = '/upload',
    PERMISSION = '/permission',
    USER = '/users',
    GRANT_PERMISSION = '/grant-permission',
    HOME = '/',
    DASHBOARD = '/dashboard',
    RELEASES = '/releases',
    RELEASES_DETAIL = '/releases/*',
    RELEASE_TYPE = '/release-type',
    TRACKS = '/tracks',
    TRACK_DETAIL = '/tracks/*',
    CREATE_RELEASE = '/release-detail',
    LABELS = '/labels',
    LABEL_DETAIL = '/labels/*',
    ARTISTS = '/artists',
    ARTIST_DETAIL = '/artists/*',
    DISTRIBUTION = '/distribution',
    LANGUAGES = '/languages',
    COUNTRIES = '/countries',
    GENRES = '/genres',
    DSP = '/dsp',
    ARTIST_ROLE = '/artist-role',
    EMAIL_SENDER = '/email-sender',
    TIMEZONE = '/timezone',
    TRACK_TYPE = '/track-types',
    TRACK_ORIGIN_TYPE = '/track-origin-types',
    TRACK_SENSITIVE = '/track-sensitive',
    TENANT = '/tenants',
    TENANT_DETAIL = '/tenants/*',
    TENANT_TIERS = '/tenant-tiers',
    TENANT_ISSUE = '/tenant-issue',
    SETTING = '/setting',
    SIGN_IN = '/sign-in',
    FORGOT_PASSWORD = '/forgot-password',
    RESET_PASSWORD = '/reset-password',
    ROLES = '/roles',
    ACTIONS = '/actions',
    CURRENCIES = '/currencies',
    PRICE_TIERS = '/price-tiers',
    ANALYTICS = '/analytics',
    ANALYTIC_DETAIL = '/analytics/*',
    ISSUE_LEVEL = '/issue-level',
    ISSUES = '/issues',
    REVENUE = '/revenue',
    NEWS_CATEGORY = '/news-category',
    NEWS = '/news',
    NEWS_DETAIL = '/news/*',
    AGGREGATOR = '/aggregator',
    DEAL_TYPE = '/deal-type',
    PING = '/ping',
}

export const AUTH_ROUTES: string[] = [APP_ROUTES.SIGN_IN];

export const DEFAULT_ROUTE = APP_ROUTES.DASHBOARD;

export const HOME_ROUTE = APP_ROUTES.DASHBOARD;

export const PUBLIC_ROUTES = [APP_ROUTES.NOT_FOUND, APP_ROUTES.SERVER_ERROR];
