export const QUERY_KEY = {
    GOOGLE_DRIVE: {
        KEY: 'GOOGLE_DRIVE',
        GET_THUMBNAIL: 'GET_THUMBNAIL',
    },
    STATISTIC: {
        KEY: 'STATISTIC',
        TOP_USER_CREATORS: 'TOP_USER_CREATORS',
        TOP_USER_COMPLETED: 'TOP_USER_COMPLETED',
        EXPORT_FILE: 'EXPORT_FILE',
        GET_ORDER_GROUP_COUNT: 'GET_ORDER_GROUP_COUNT',
        GET_ORDER_PRODUCT_GROUP_COUNT: 'GET_ORDER_PRODUCT_GROUP_COUNT',
    },
    IMAGE: {
        KEY: 'IMAGE',
    },
    USER: {
        KEY: 'USER',
        GET_USER_LIST: 'GET_USER_LIST',
        GET_USER_LIST_ALL: 'GET_USER_LIST_ALL',
        GET_PROFILE: 'GET_PROFILE',
        GET_USER_DETAIL: 'GET_USER_DETAIL',
        GET_PERMISSION: 'GET_PERMISSION',
        GET_ROLE: 'GET_ROLE',
    },
    NETWORK: {
        KEY: 'NETWORK',
        GET_NETWORK_LIST: 'GET_NETWORK_LIST',
        GET_NETWORK_LIST_ALL: 'GET_NETWORK_LIST_ALL',
        GET_NETWORK_DETAIL: 'GET_NETWORK_DETAIL',
        GET_NETWORK_GRAPH: 'GET_NETWORK_GRAPH',
    },
    PROJECT: {
        KEY: 'PROJECT',
        GET_PROJECT_LIST: 'GET_PROJECT_LIST',
        GET_PROJECT_LIST_ALL: 'GET_PROJECT_LIST_ALL',
        GET_PROJECT_DETAIL: 'GET_PROJECT_DETAIL',
    },
    NOTIFICATION: {
        KEY: 'NOTIFICATION',
        GET_NOTIFICATION_LIST: 'GET_NOTIFICATION_LIST',
    },
    DASHBOARD: {
        KEY: 'DASHBOARD',
        GET_NETWORK: 'GET_DASHBOARD_NETWORK',
        GET_CHANNEL: 'GET_DASHBOARD_CHANNEL',
        GET_STATS: 'GET_DASHBOARD_STATS',
        GET_PARTNER: 'GET_DASHBOARD_PARTNER',
        GET_COUNT_ISSUE: 'GET_COUNT_ISSUE',
        GET_COUNT_OVERVIEW: 'GET_COUNT_OVERVIEW',
        GET_COUNT_COUNTRY: 'GET_COUNT_COUNTRY',
    },
    GROUP: {
        KEY: 'GROUP',
        GET_GROUP_LIST: 'GET_GROUP_LIST',
        GET_GROUP_LIST_ALL: 'GET_GROUP_LIST_ALL',
        GET_GROUP_DETAIL: 'GET_GROUP_DETAIL',
    },
    HOME: {
        KEY: 'HOME',
        GET_HOME_SECTION_LIST: 'GET_HOME_SECTION_LIST',
        GET_HOME_SECTION_DETAIL: 'GET_HOME_SECTION_DETAIL',
    },
    CHANNEL: {
        KEY: 'CHANNEL',
        GET_CHANNEL_LIST: 'GET_CHANNEL_LIST',
        GET_CHANNEL_LIST_SIMPLE: 'GET_CHANNEL_LIST_SIMPLE',
        GET_CHANNEL_LIST_ALL: 'GET_CHANNEL_LIST_ALL',
        GET_CHANNEL_LIST_WARNING: 'GET_CHANNEL_LIST_WARNING',
        GET_CHANNEL_DETAIL: 'GET_CHANNEL_DETAIL',
        GET_CHANNEL_DETAIL_REV: 'GET_CHANNEL_DETAIL_REV',
        GET_CHANNEL_SIDEBAR: 'GET_CHANNEL_SIDEBAR',
        GET_CHANNEL_SIDEBAR_NETWORK: 'GET_CHANNEL_SIDEBAR_NETWORK',
        GET_CHANNEL_SIDEBAR_PARTNER: 'GET_CHANNEL_SIDEBAR_PARTNER',
        GET_CHANNEL_SIDEBAR_PROJECT: 'GET_CHANNEL_SIDEBAR_PROJECT',
        GET_CHANNEL_SIDEBAR_AUTH: 'GET_CHANNEL_SIDEBAR_AUTH',
        GET_CHANNEL_SIDEBAR_MONETIZE: 'GET_CHANNEL_SIDEBAR_MONETIZE',
        GET_CHANNEL_GRAPH: 'GET_CHANNEL_GRAPH',
        GET_CHANNEL_ANALYTIC: 'GET_CHANNEL_ANALYTIC',
        GET_CHANNEL_PARTNER_OVERVIEW: 'GET_CHANNEL_PARTNER_OVERVIEW',
        GET_CHANNEL_NETWORK_OVERVIEW: 'GET_CHANNEL_NETWORK_OVERVIEW',
        GET_CHANNEL_HISTORY: 'GET_CHANNEL_HISTORY',
    },
    VIDEO: {
        KEY: 'VIDEO',
        GET_VIDEO_LIST: 'GET_VIDEO_LIST',
        GET_VIDEO_LIST_ALL: 'GET_VIDEO_LIST_ALL',
        GET_VIDEO_DETAIL: 'GET_VIDEO_DETAIL',
        GET_VIDEO_SIDEBAR_NETWORK: 'GET_VIDEO_SIDEBAR_NETWORK',
        GET_VIDEO_SIDEBAR_PARTNER: 'GET_VIDEO_SIDEBAR_PARTNER',
        GET_VIDEO_SIDEBAR_PROJECT: 'GET_VIDEO_SIDEBAR_PROJECT',
        GET_VIDEO_SIDEBAR_CHANNEL: 'GET_VIDEO_SIDEBAR_CHANNEL',
        GET_VIDEO_SIDEBAR_VISIBILITY: 'GET_VIDEO_SIDEBAR_VISIBILITY',
        GET_VIDEO_SYNC_CHANNEL: 'GET_VIDEO_SYNC_CHANNEL',
        GET_VIDEO_SIDEBAR_REVIEW_STATUS: 'GET_VIDEO_SIDEBAR_REVIEW_STATUS',
        GET_VIDEO_SIDEBAR_VIDEO_TYPE: 'GET_VIDEO_SIDEBAR_VIDEO_TYPE',
        GET_VIDEO_SIDEBAR_MADE_FOR_KIDS: 'GET_VIDEO_SIDEBAR_MADE_FOR_KIDS',
        GET_VIDEO_REVENUE: 'GET_VIDEO_REVENUE',
    },
    SETTING: {
        KEY: 'SETTING',
        GET_SETTING: 'GET_SETTING',
        GET_SETTING_PRIVATE: 'GET_SETTING_PRIVATE',
        GET_SETTING_PUBLIC: 'GET_SETTING_PUBLIC',
        GET_WEB_SETTING: 'GET_WEB_SETTING',
        UPDATE: 'UPDATE_SETTING',
    },
    PRIVACY: {
        KEY: 'PRIVACY',
        GET_PRIVACY: 'GET_PRIVACY',
    },
    PARTNER: {
        KEY: 'PARTNER',
        GET_PARTNER_LIST: 'GET_PARTNER_LIST',
        GET_PARTNER_LIST_ALL: 'GET_PARTNER_LIST_ALL',
        GET_PARTNER_DETAIL: 'GET_PARTNER_DETAIL',
        GET_PARTNER_GRAPH: 'GET_PARTNER_GRAPH',
    },
    DEPARTMENT: {
        KEY: 'DEPARTMENT',
        GET_DEPARTMENT_LIST: 'GET_DEPARTMENT_LIST',
        GET_DEPARTMENT_SIGN_UP: 'GET_DEPARTMENT_SIGN_UP',
        GET_DEPARTMENT_DETAIL: 'GET_DEPARTMENT_DETAIL',
    },
    PERMISSION: {
        KEY: 'PERMISSION',
        GET_USER_PERMISSION: 'GET_USER_PERMISSION',
        GET_GROUP_PERMISSION: 'GET_GROUP_PERMISSION',
        GET_LIST_PERMISSION: 'GET_LIST_PERMISSION',
        GET_LIST_SIMPLE_PERMISSION: 'GET_LIST_SIMPLE_PERMISSION',
        GET_DETAIL_PERMISSION: 'GET_DETAIL_PERMISSION',
    },
    LOG: {
        KEY: 'LOG',
        GET_LOGS_LIST: 'GET_LOGS_LIST',
        GET_LOGS_MODULES: 'GET_LOGS_MODULES',
    },
    CHANNEL_LOG: {
        KEY: 'CHANNEL_LOG',
        GET_CHANNEL_LOG_LIST: 'GET_CHANNEL_LOG_LIST',
    },
    CLIENT: {
        KEY: 'CLIENT',
        GET_CLIENT_ROLE_USER: 'GET_CLIENT_ROLE_USER',
        GET_CLIENT_ROLE_GROUP: 'GET_CLIENT_ROLE_GROUP',
    },
    ROLE: {
        KEY: 'ROLE',
        GET_ROLE_LIST: 'GET_ROLE_LIST',
        GET_ROLE_LIST_ALL: 'GET_ROLE_LIST_ALL',
        GET_ROLE_DETAIL: 'GET_ROLE_DETAIL',
        GET_ROLE_LIST_ALL_DETAIL: 'GET_ROLE_LIST_ALL_DETAIL',
    },
    COUNTRIES: {
        KEY: 'COUNTRIES',
        GET_LIST: 'GET_LIST_COUNTRIES',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_COUNTRIES',
        GET_DETAIL: 'GET_DETAIL_COUNTRIES',
    },
    LANGUAGE: {
        KEY: 'LANGUAGE',
        GET_LIST: 'GET_LIST_LANGUAGE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_LANGUAGE',
        GET_DETAIL: 'GET_DETAIL_LANGUAGE',
    },
    GENRE: {
        KEY: 'GENRE',
        GET_LIST: 'GET_LIST_GENRE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_GENRE',
        GET_DETAIL: 'GET_DETAIL_GENRE',
    },
    LABELS: {
        KEY: 'LABELS',
        GET_LIST: 'GET_LIST_LABELS',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_LABELS',
        GET_DETAIL: 'GET_DETAIL_LABELS',
    },
    ARTIST: {
        KEY: 'ARTIST',
        GET_LIST: 'GET_LIST_ARTIST',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_ARTIST',
        GET_DETAIL: 'GET_LIST_ARTIST',
    },
    ARTIST_ROLE: {
        KEY: 'ARTIST_ROLE',
        GET_LIST: 'GET_LIST_ARTIST_ROLE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_ARTIST_ROLE',
        GET_DETAIL: 'GET_DETAIL_ARTIST_ROLE',
    },
    DSP: {
        KEY: 'DPS',
        GET_LIST: 'GET_LIST_DSP',
        GET_DETAIL: 'GET_DETAIL_DSP',
        UPDATE: 'UPDATE_DSP',
        GET_DETAIL_ROUTING_CONFIG: 'GET_DETAIL_DSP',
    },
    DSP_REPORT: {
        KEY: 'DSP_REPORT',
        GET_LIST: 'GET_LIST_DSP_REPORT',
        GET_DETAIL: 'GET_DETAIL_DSP_REPORT',
        GET_FTP_PARSER_CONFIGS: 'GET_FTP_PARSER_CONFIGS_DSP_REPORT',
    },
    PG_DSPS_SYNC: {
        KEY: 'PG_DSPS_SYNC',
        GET_LIST: 'GET_LIST_PG_DSPS_SYNC',
    },
    DSP_SYSTEM: {
        KEY: 'DPS_SYSTEM',
        GET_LIST: 'GET_LIST_DSP_SYSTEM',
        GET_DETAIL: 'GET_DETAIL_DSP_SYSTEM',
        UPDATE: 'UPDATE_DSP_SYSTEM',
    },
    DSP_ACTION: {
        KEY: 'DPS_ACTION',
        GET_LIST: 'GET_LIST_DSP_ACTION',
        GET_DETAIL: 'GET_DETAIL_DSP_ACTION',
    },
    RELEASES: {
        KEY: 'RELEASES',
        GET_LIST: 'GET_LIST_RELEASES',
        GET_DETAIL: 'GET_DETAIL_RELEASES',
        VALIDATE: 'VALIDATE_RELEASE',
        GET_ENRICHED_ERRORS: 'GET_ENRICHED_ERRORS_RELEASE',
        DOWNLOAD_ASSET: 'DOWNLOAD_ASSETS_RELEASE',
        GET_CAPTIONS: 'GET_CAPTIONS_RELEASE',
        GET_RELEASE_REVIEWS: 'GET_RELEASE_REVIEWS_RELEASE',
    },
    TIMEZONE: {
        KEY: 'TIMEZONE',
        GET_LIST: 'GET_LIST_TIMEZONE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_TIMEZONE',
        GET_DETAIL: 'GET_DETAIL_TIMEZONE',
    },
    RELEASE_ARTIST: {
        KEY: 'RELEASE_ARTIST',
        GET_LIST: 'GET_LIST_RELEASE_ARTIST',
        GET_DETAIL: 'GET_DETAIL_RELEASE_ARTIST',
    },
    RELEASE_CONTRIBUTOR: {
        KEY: 'RELEASE_CONTRIBUTOR',
        GET_LIST: 'GET_LIST_RELEASE_CONTRIBUTOR',
        GET_DETAIL: 'GET_DETAIL_RELEASE_CONTRIBUTOR',
    },
    RELEASE_TYPE: {
        KEY: 'RELEASE_TYPE',
        GET_LIST: 'GET_LIST_RELEASE_TYPE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_RELEASE_TYPE',
        GET_DETAIL: 'GET_DETAIL_RELEASE_TYPE',
    },
    TRACK: {
        KEY: 'TRACK',
        GET_LIST: 'GET_LIST_TRACK',
        GET_DETAIL: 'GET_DETAIL_TRACK',
        GET_LIST_BY_RELEASE_ID: 'TRACK_GET_LIST_TRACK_BY_RELEASE_ID',
        GET_TRACKS_POLICIES: 'GET_TRACKS_POLICIES',
    },
    TRACK_REVENUE: {
        KEY: 'TRACK_REVENUE',
        GET_LIST: 'GET_LIST_TRACK_REVENUE',
    },
    TRACK_SENSITIVE: {
        KEY: 'TRACK_SENSITIVE',
        GET_LIST: 'GET_LIST_TRACK_SENSITIVE',
        UPDATE: 'UPDATE_TRACK_SENSITIVE',
    },
    TRACK_ARTIST: {
        KEY: 'TRACK_ARTIST',
        GET_LIST: 'GET_LIST_TRACK_ARTIST',
    },
    TRACK_CONTRIBUTOR: {
        KEY: 'TRACK_CONTRIBUTOR',
        GET_LIST: 'GET_LIST_TRACK_CONTRIBUTOR',
    },
    TRACK_TYPE: {
        KEY: 'TRACK_TYPE',
        GET_LIST: 'GET_LIST_TRACK_TYPE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_TRACK_TYPE',
        GET_DETAIL: 'GET_DETAIL_TRACK_TYPE',
        UPDATE: 'TRACK_TYPE_UPDATE',
    },
    TRACK_ORIGIN_TYPE: {
        KEY: 'TRACK_ORIGIN_TYPE',
        GET_LIST: 'GET_LIST_TRACK_ORIGIN_TYPE',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_TRACK_ORIGIN_TYPE',
        GET_DETAIL: 'GET_DETAIL_TRACK_ORIGIN_TYPE',
        UPDATE: 'UPDATE_TRACK_ORIGIN_TYPE',
    },
    TENANT: {
        KEY: 'TENANT',
        GET_LIST: 'GET_LIST_TENANT',
        GET_ACTIVE: 'GET_ACTIVE_TENANT',
        GET_ACTIVE_ACCESSIBLE: 'GET_ACTIVE_ACCESSIBLE_TENANT',
        GET_DETAIL: 'GET_DETAIL_TENANT',
        GET_DSP: 'GET_TENANT_DSP',
        GET_DSP_AGREEMENT: 'GET_TENANT_DSP_AGREEMENT',
        GET_DSP_AGREEMENT_USER: 'GET_TENANT_DSP_AGREEMENT_USER',
        GET_ROLES: 'GET_TENANT_ROLES',
        UPDATE: 'UPDATE_TENANT',
        CREATE: 'CREATE_TENANT',
        CREATE_DOMAIN: 'CREATE_TENANT_DOMAIN',
        RESOLVE_DOMAIN: 'RESOLVE_DOMAIN',
        VERIFY_DOMAIN: 'VERIFY_TENANT_DOMAIN',
        GET_DOMAIN: 'GET_TENANT_DOMAIN',
        GET_CF_OAUTH_URL: 'GET_TENANT_CF_OAUTH_URL',
    },
    TENANT_TIERS: {
        KEY: 'TENANT_TIERS',
        GET_LIST: 'GET_LIST_TENANT_TIERS',
        UPDATE: 'UPDATE_TENANT_TIERS',
        CREATE: 'CREATE_TENANT_TIERS',
    },
    TENANT_ISSUE: {
        KEY: 'TENANT_ISSUE',
        GET_LIST: 'GET_LIST_TENANT_ISSUE',
        UPDATE: 'UPDATE_TENANT_ISSUE',
        CREATE: 'CREATE_TENANT_ISSUE',
    },
    ACR_CLOUD: {
        KEY: 'ACR_CLOUD',
        GET_LIST: 'ACR_CLOUD_GET_LIST',
        GET_DETAIL: 'ACR_CLOUD_GET_DETAIL',
        GET_LIST_SCAN_STATUS: 'ACR_CLOUD_GET_LIST_SCAN_STATUS',
        GET_DETAIL_SCAN_STATUS: 'ACR_COULD_GET_DETAIL_SCAN_STATUS',
    },
    ACTIONS: {
        KEY: 'ACTIONS',
        GET_LIST: 'GET_LIST_ACTIONS',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_ACTIONS',
        GET_DETAIL: 'GET_DETAIL_ACTIONS',
    },
    CURRENCIES: {
        KEY: 'CURRENCIES',
        GET_LIST: 'GET_LIST_CURRENCIES',
        GET_LIST_SIMPLE: 'GET_LIST_SIMPLE_CURRENCIES',
        GET_DETAIL: 'GET_DETAIL_CURRENCIES',
    },
    PRICE_TIERS: {
        KEY: 'PRICE_TIERS',
        GET_LIST: 'GET_LIST_PRICE_TIERS',
        GET_DETAIL: 'GET_DETAIL_PRICE_TIERS',
        UPDATE: 'UPDATE_PRICE_TIERS',
    },
    BACKUP_DATABASE: {
        KEY: 'BACKUP_DATABASE',
        GET_LIST: 'GET_LIST_DATABASE_LOGS',
    },
    ISSUES: {
        KEY: 'ISSUES',
        GET_LIST: 'GET_LIST_ISSUES',
        UPDATE: 'UPDATE_ISSUES',
    },
    ISSUE_LEVEL: {
        KEY: 'ISSUE_LEVEL',
        GET_LIST: 'GET_LIST_ISSUE_LEVEL',
        UPDATE: 'UPDATE_ISSUE_LEVEL',
    },
    NEWS_CATEGORY: {
        KEY: 'NEWS_CATEGORY',
        GET_LIST: 'GET_LIST_NEWS_CATEGORY',
        GET_TREE: 'GET_TREE_NEWS_CATEGORY',
        UPDATE: 'UPDATE_NEWS_CATEGORY',
    },
    NEWS: {
        KEY: 'NEWS',
        GET_LIST: 'GET_LIST_NEWS',
        UPDATE: 'UPDATE_NEWS',
        GET_DETAIL_TRANSLATION: 'GET_DETAIL_TRANSLATION',
        GET_LIST_TRANSLATIONS: 'GET_LIST_TRANSLATIONS',
    },
    AGGREGATOR: {
        KEY: 'AGGREGATOR',
        GET_LIST: 'GET_LIST_AGGREGATOR',
        UPDATE: 'UPDATE_AGGREGATOR',
        GET_DETAIL: 'GET_DETAIL_AGGREGATOR',
    },
    REPORT_CONFIG: {
        KEY: 'REPORT_CONFIG',
        GET_LIST: 'GET_LIST_REPORT_CONFIG',
        UPDATE: 'UPDATE_REPORT_CONFIG',
        GET_DETAIL: 'GET_DETAIL_REPORT_CONFIG',
    },
    ETL_JOBS: {
        KEY: 'ETL_JOBS',
        GET_LIST: 'GET_LIST_ETL_JOBS',
        GET_STATUS_DETAIL: 'GET_STATUS_DETAIL_ETL_JOB',
    },
    ENRICH_SCAN_SESSIONS: {
        KEY: 'ENRICH_SCAN_SESSIONS',
        GET_LIST: 'GET_LIST_ENRICH_SCAN_SESSIONS',
    },
    ENRICH_SCAN_SCHEDULES: {
        KEY: 'ENRICH_SCAN_SCHEDULES',
        GET_LIST: 'GET_LIST_ENRICH_SCAN_SCHEDULES',
    },
    ENRICH_HISTORY: {
        KEY: 'ENRICH_HISTORY',
        GET_LIST: 'GET_LIST_ENRICH_HISTORY',
    },
    ETL_SYNC_CONFIG: {
        KEY: 'ETL_SYNC_CONFIG',
    },
    SPOTIFY_R2_SYNC_CONFIG: {
        KEY: 'SPOTIFY_R2_SYNC_CONFIG',
    },
    SPOTIFY_EXPORT_SCHEDULER_CONFIG: {
        KEY: 'SPOTIFY_EXPORT_SCHEDULER_CONFIG',
    },
    FTP_EXCLUDE_PATTERN: {
        KEY: 'FTP_EXCLUDE_PATTERNS',
        GET_LIST: 'GET_LIST_FTP_EXCLUDE_PATTERNS',
        GET_DETAIL: 'GET_DETAIL_FTP_EXCLUDE_PATTERNS',
        UPDATE: 'UPDATE_FTP_EXCLUDE_PATTERNS',
    },
    INTEGRATION: {
        KEY: 'INTEGRATION',
        GET_LIST: 'GET_LIST_INTEGRATION',
        UPDATE: 'UPDATE_INTEGRATION',
        GET_DETAIL: 'GET_DETAIL_INTEGRATION',
    },
    DEAL_TYPE: {
        KEY: 'DEAL_TYPE',
        GET_LIST: 'GET_LIST_DEAL_TYPE',
        UPDATE: 'UPDATE_DEAL_TYPE',
        GET_DETAIL: 'GET_DETAIL_DEAL_TYPE',
    },
    DSP_DEAL: {
        KEY: 'DSP_DEAL',
        GET_LIST: 'GET_LIST_DSP_DEAL',
        UPDATE: 'UPDATE_DSP_DEAL',
        GET_DETAIL: 'GET_DETAIL_DSP_DEAL',
    },

    RELEASE_DSP: {
        KEY: 'RELEASE_DSP',
        GET_LIST: 'GET_LIST_RELEASE_DSP',
        UPDATE: 'UPDATE_RELEASE_DSP',
        GET_DETAIL: 'GET_DETAIL_RELEASE_DSP',
    },

    PREFIX_ISRC: {
        KEY: 'PREFIX_ISRC',
        GET_DETAIL_PREFIX_ISRC: 'GET_DETAIL_PREFIX_ISRC',
        GET_LIST_PREFIX_ISRC: 'GET_LIST_PREFIX_ISRC',
    },

    PREFIX_UPC: {
        KEY: 'PREFIX_UPC',
        GET_DETAIL_PREFIX_UPC: 'GET_DETAIL_PREFIX_UPC',
        GET_LIST_PREFIX_UPC: 'GET_LIST_PREFIX_UPC',
    },

    RELEASE_LOG: {
        KEY: 'RELEASE_LOG',
        GET_LIST: 'GET_LIST_RELEASE_LOG',
    },
    RELEASE_EXECUTION: {
        KEY: 'RELEASE_EXECUTION',
        GET_LIST: 'GET_LIST_RELEASE_EXECUTION',
        RETRY: 'RETRY_RELEASE_EXECUTION',
    },

    DISTRIBUTION_JOB: {
        KEY: 'DISTRIBUTION_JOB',
        GET_LIST: 'GET_LIST_DISTRIBUTION_JOB',
        GET_LIST_GROUPED: 'GET_LIST_DISTRIBUTION_JOB_GROUPED',
    },

    RELEASE_VIDEO: {
        KEY: 'RELEASE_VIDEO',
        GET_LIST: 'GET_LIST_RELEASE_VIDEO',
        GET_DETAIL: 'GET_DETAIL_RELEASE_VIDEO',
    },
    ANALYTICS2: {
        KEY: 'ANALYTICS2',
        ANALYTICS_SUMMARY: 'analytics-summary',
        DSP_TIMELINE: 'dsp-timeline',
        TER_TIMELINE: 'ter-timeline',
        TREND_VIEW_SUMMARY: 'trend-view-summary',
        TREND_VIEW_LINE_CHART: 'trend-view-line-chart',
        TREND_VIEW_DSP_BAR_CHART: 'trend-view-dsp-bar-chart',
        TREND_VIEW_TER_BAR_CHART: 'trend-view-ter-bar-chart',
        DSP_SALES_TIMELINE: 'dsp-sales-timeline',
        DSP_DAILY_TIMELINE: 'dsp-daily-timeline',
        TRACK_RANKING: 'track-ranking',
        RELEASE_RANKING: 'release-ranking',
        RELEASE_VIDEO_RANKING: 'release-video-ranking',
        ARTIST_RANKING: 'artist-ranking',
        LABEL_RANKING: 'label-ranking',
        TENANT_RANKING: 'tenant-ranking',
        DSP_RANKING: 'dsp-ranking',
        CHANNEL_RANKING: 'channel-ranking',
        SYNC_JOB: 'SYNC_JOB',
        REVENUE_SUMMARY: 'revenue-summary',
        REVENUE_LINE_CHART: 'revenue-line-chart',
        REVENUE_DSP_BAR_CHART: 'revenue-dsp-bar-chart',
        REVENUE_TER_BAR_CHART: 'revenue-ter-bar-chart',
        REVENUE_TIMELINE: 'revenue-timeline',
        REVENUE_TOP_DSP: 'revenue-top-dsp',
        REVENUE_TOP_TENANT: 'revenue-top-tenant',
        REVENUE_TOP_ARTIST: 'revenue-top-artist',
        REVENUE_TOP_TRACK: 'revenue-top-track',
        REVENUE_TOP_RELEASE: 'revenue-top-release',
        REVENUE_TOP_RELEASE_VIDEO: 'revenue-top-release-video',
        REVENUE_TOP_LABEL: 'revenue-top-label',
        REVENUE_TOP_CHANNEL: 'revenue-top-channel',
        REVENUE_TOP_SOURCE_TYPE: 'revenue-top-source-type',
        RELEASE_OVERVIEW: 'release-overview',
        RELEASE_DSP_TIMELINE: 'release-dsp-timeline',
        RELEASE_DSP_SALES_TIMELINE: 'release-dsp-sales-timeline',
        RELEASE_DSP_DAILY_TIMELINE: 'release-dsp-daily-timeline',
        RELEASE_REVENUE_TIMELINE: 'release-revenue-timeline',
        RELEASE_TREND_VIEW_LINE_CHART: 'release-trend-view-line-chart',
        RELEASE_TREND_VIEW_DSP_BAR_CHART: 'release-trend-view-dsp-bar-chart',
        RELEASE_TREND_VIEW_TER_BAR_CHART: 'release-trend-view-ter-bar-chart',
        RELEASE_REVENUE_LINE_CHART: 'release-revenue-line-chart',
        RELEASE_REVENUE_DSP_BAR_CHART: 'release-revenue-dsp-bar-chart',
        RELEASE_REVENUE_TER_BAR_CHART: 'release-revenue-ter-bar-chart',
        RELEASE_DSP: 'release-dsp',
        RELEASE_TER: 'release-ter',
        TRACK_OVERVIEW: 'track-overview',
        TRACK_REVENUE_LINE_CHART: 'track-revenue-line-chart',
        TRACK_REVENUE_DSP_BAR_CHART: 'track-revenue-dsp-bar-chart',
        TRACK_REVENUE_TER_BAR_CHART: 'track-revenue-ter-bar-chart',
        TRACK_TREND_VIEW_LINE_CHART: 'track-trend-view-line-chart',
        TRACK_TREND_VIEW_DSP_BAR_CHART: 'track-trend-view-dsp-bar-chart',
        TRACK_TREND_VIEW_TER_BAR_CHART: 'track-trend-view-ter-bar-chart',
        TRACK_DSP_TIMELINE: 'track-dsp-timeline',
        TRACK_DSP_SALES_TIMELINE: 'track-dsp-sales-timeline',
        TRACK_DSP_DAILY_TIMELINE: 'track-dsp-daily-timeline',
        TRACK_REVENUE_TIMELINE: 'track-revenue-timeline',
        TRACK_DSP: 'track-dsp',
        TRACK_TER: 'track-ter',
        LABEL_OVERVIEW: 'label-overview',
        LABEL_SUMMARY: 'label-summary',
        LABEL_DSP_TIMELINE: 'label-dsp-timeline',
        LABEL_DSP_SALES_TIMELINE: 'label-dsp-sales-timeline',
        LABEL_DSP_DAILY_TIMELINE: 'label-dsp-daily-timeline',
        LABEL_REVENUE_TIMELINE: 'label-revenue-timeline',
        LABEL_TREND_VIEW_LINE_CHART: 'label-trend-view-line-chart',
        LABEL_TREND_VIEW_DSP_BAR_CHART: 'label-trend-view-dsp-bar-chart',
        LABEL_TREND_VIEW_TER_BAR_CHART: 'label-trend-view-ter-bar-chart',
        LABEL_REVENUE_LINE_CHART: 'label-revenue-line-chart',
        LABEL_REVENUE_DSP_BAR_CHART: 'label-revenue-dsp-bar-chart',
        LABEL_REVENUE_TER_BAR_CHART: 'label-revenue-ter-bar-chart',
        LABEL_TOP_RELEASES: 'label-top-releases',
        LABEL_TOP_TRACKS: 'label-top-tracks',
        LABEL_DSP: 'label-dsp',
        LABEL_TER: 'label-ter',
        ARTIST_OVERVIEW: 'artist-overview',
        ARTIST_SUMMARY: 'artist-summary',
        ARTIST_TOP_RELEASES: 'artist-top-releases',
        ARTIST_TOP_TRACKS: 'artist-top-tracks',
        ARTIST_DSP_TIMELINE: 'artist-dsp-timeline',
        ARTIST_DSP_SALES_TIMELINE: 'artist-dsp-sales-timeline',
        ARTIST_DSP_DAILY_TIMELINE: 'artist-dsp-daily-timeline',
        ARTIST_REVENUE_TIMELINE: 'artist-revenue-timeline',
        ARTIST_TREND_VIEW_LINE_CHART: 'artist-trend-view-line-chart',
        ARTIST_TREND_VIEW_DSP_BAR_CHART: 'artist-trend-view-dsp-bar-chart',
        ARTIST_TREND_VIEW_TER_BAR_CHART: 'artist-trend-view-ter-bar-chart',
        ARTIST_REVENUE_LINE_CHART: 'artist-revenue-line-chart',
        ARTIST_REVENUE_DSP_BAR_CHART: 'artist-revenue-dsp-bar-chart',
        ARTIST_REVENUE_TER_BAR_CHART: 'artist-revenue-ter-bar-chart',
        ARTIST_DSP: 'artist-dsp',
        ARTIST_TER: 'artist-ter',
        TENANT_OVERVIEW: 'tenant-overview',
        TENANT_TOP_RELEASES: 'tenant-top-releases',
        TENANT_TOP_TRACKS: 'tenant-top-tracks',
        TENANT_TREND_VIEW_LINE_CHART: 'tenant-trend-view-line-chart',
        TENANT_TREND_VIEW_DSP_BAR_CHART: 'tenant-trend-view-dsp-bar-chart',
        TENANT_TREND_VIEW_TER_BAR_CHART: 'tenant-trend-view-ter-bar-chart',
        TENANT_REVENUE_LINE_CHART: 'tenant-revenue-line-chart',
        TENANT_REVENUE_DSP_BAR_CHART: 'tenant-revenue-dsp-bar-chart',
        TENANT_REVENUE_TER_BAR_CHART: 'tenant-revenue-ter-bar-chart',
        TENANT_DSP: 'tenant-dsp',
        TENANT_TER: 'tenant-ter',
        CHANNEL_OVERVIEW: 'channel-overview',
        CHANNEL_TOP_RELEASES: 'channel-top-releases',
        CHANNEL_TREND_VIEW_LINE_CHART: 'channel-trend-view-line-chart',
        CHANNEL_TREND_VIEW_DSP_BAR_CHART: 'channel-trend-view-dsp-bar-chart',
        CHANNEL_TREND_VIEW_TER_BAR_CHART: 'channel-trend-view-ter-bar-chart',
        CHANNEL_REVENUE_LINE_CHART: 'channel-revenue-line-chart',
        CHANNEL_REVENUE_DSP_BAR_CHART: 'channel-revenue-dsp-bar-chart',
        CHANNEL_REVENUE_TER_BAR_CHART: 'channel-revenue-ter-bar-chart',
        CHANNEL_DSP: 'channel-dsp',
        CHANNEL_TER: 'channel-ter',
        DSP_OVERVIEW: 'dsp-overview',
        DSP_SUMMARY: 'dsp-summary',
        DSP_TOP_RELEASES: 'dsp-top-releases',
        DSP_TOP_TRACKS: 'dsp-top-tracks',
        DSP_TREND_VIEW_LINE_CHART: 'dsp-trend-view-line-chart',
        DSP_TREND_VIEW_TER_BAR_CHART: 'dsp-trend-view-ter-bar-chart',
        DSP_TREND_VIEW_TENANT_BAR_CHART: 'dsp-trend-view-tenant-bar-chart',
        DSP_REVENUE_LINE_CHART: 'dsp-revenue-line-chart',
        DSP_REVENUE_TER_BAR_CHART: 'dsp-revenue-ter-bar-chart',
        DSP_REVENUE_TENANT_BAR_CHART: 'dsp-revenue-tenant-bar-chart',
        SOURCE_TYPE_OVERVIEW: 'source-type-overview',
        SOURCE_TYPE_TOP_RELEASES: 'source-type-top-releases',
        SOURCE_TYPE_TOP_TRACKS: 'source-type-top-tracks',
        SOURCE_TYPE_REVENUE_LINE_CHART: 'source-type-revenue-line-chart',
        SOURCE_TYPE_TREND_VIEW_LINE_CHART: 'source-type-trend-view-line-chart',
        SOURCE_TYPE_REVENUE_DSP_BAR_CHART: 'source-type-revenue-dsp-bar-chart',
        SOURCE_TYPE_REVENUE_TER_BAR_CHART: 'source-type-revenue-ter-bar-chart',
        SOURCE_TYPE_TREND_VIEW_DSP_BAR_CHART: 'source-type-trend-view-dsp-bar-chart',
        SOURCE_TYPE_TREND_VIEW_TER_BAR_CHART: 'source-type-trend-view-ter-bar-chart',
        SOURCE_TYPE_RANKING: 'source-type-ranking',
    },
    YOUTUBE_KEY: {
        KEY: 'YOUTUBE_KEY',
        GET_YOUTUBE_KEYS_LIST: 'GET_YOUTUBE_KEYS_LIST',
        GET_YOUTUBE_KEY_DETAIL: 'GET_YOUTUBE_KEY_DETAIL',
    },
};
