import { TRACKS_COLUMNS_DISPLAY } from '../enums';

export const defaultVisibleColumnsTracks = [
    TRACKS_COLUMNS_DISPLAY.I_NO,
    TRACKS_COLUMNS_DISPLAY.THUMBNAIL,
    // TRACKS_COLUMNS_DISPLAY.ID,
    TRACKS_COLUMNS_DISPLAY.TITLE,
    TRACKS_COLUMNS_DISPLAY.VERSION,
    TRACKS_COLUMNS_DISPLAY.GENRES,
    TRACKS_COLUMNS_DISPLAY.TRACK_ARTIST,
    TRACKS_COLUMNS_DISPLAY.ISRC,
    TRACKS_COLUMNS_DISPLAY.ACR_CLOUD,
    // TRACKS_COLUMNS_DISPLAY.RELEASE_DATE,
    // TRACKS_COLUMNS_DISPLAY.CREATED_AT,
    TRACKS_COLUMNS_DISPLAY.ACTIONS,
];

export const MAX_COUNT_UPLOAD_TRACK = 200;
