import { TRACKS_COLUMNS_DISPLAY } from '../enums';

export const defaultVisibleColumnsTracks = [
    TRACKS_COLUMNS_DISPLAY.THUMBNAIL,
    TRACKS_COLUMNS_DISPLAY.TRACK_ID,
    TRACKS_COLUMNS_DISPLAY.TITLE,
    TRACKS_COLUMNS_DISPLAY.GENRES,
    TRACKS_COLUMNS_DISPLAY.ARTIST,
    TRACKS_COLUMNS_DISPLAY.ISRC,
    TRACKS_COLUMNS_DISPLAY.DURATION,
    // TRACKS_COLUMNS_DISPLAY.RELEASE_DATE,
    // TRACKS_COLUMNS_DISPLAY.CREATION_DATE,
    TRACKS_COLUMNS_DISPLAY.ACTIONS,
];
