import { GENRES } from '../enums';
import { TrackData } from '../types';

export const fakeTrackData: TrackData[] = [
    {
        id: 'track_001',
        title: 'Lost Echoes',
        trackId: 'rel_001',
        trackName: 'Lost Echoes',
        genres: GENRES.BLUES,
        labelName: 'Echo Records',
        isrc: 'US-ECR-25-00001',
        creationDate: '2025-03-01T10:00:00.000Z',
        releaseDate: '2025-03-10T00:00:00.000Z',
        duration: 210,
        thumbnail: 'https://picsum.photos/seed/track001/300/300',
        artists: [
            {
                id: 'artist_001',
                name: 'Lana Vee',
                role: 'main',
                artistId: 'artist_001',
                thumbnail: 'https://picsum.photos/seed/artist001/300/300',
                createdAt: new Date('2025-03-01T10:00:00.000Z'),
            },
        ],
        plays: 1200,
        isSensitiveContent: false,
        file: new File([], 'lost_echoes.mp3'),
        fileName: 'lost_echoes.mp3',
        songInfo: {
            duration: 210,
            peakData: Array(210)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_002',
        title: 'Through the Storm',
        trackId: 'rel_002',
        trackName: 'Through the Storm',
        genres: GENRES.CLASSICAL,
        labelName: 'Skyline Sounds',
        isrc: 'US-SKY-25-00002',
        creationDate: '2025-02-10T08:30:00.000Z',
        releaseDate: '2025-03-01T00:00:00.000Z',
        duration: 195,
        thumbnail: 'https://picsum.photos/seed/track002/300/300',
        artists: [
            {
                id: 'artist_002',
                name: 'Noah Reed',
                role: 'main',
                artistId: 'artist_002',
                thumbnail: 'https://picsum.photos/seed/artist002/300/300',
                createdAt: new Date('2025-02-10T08:30:00.000Z'),
            },
        ],
        plays: 980,
        isSensitiveContent: false,
        file: new File([], 'through_the_storm.mp3'),
        fileName: 'through_the_storm.mp3',
        songInfo: {
            duration: 195,
            peakData: Array(195)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_003',
        title: 'Sunset Lullaby',
        trackId: 'rel_003',
        trackName: 'Sunset Lullaby',
        genres: GENRES.CLASSICAL,
        labelName: 'Golden Hour Records',
        isrc: 'US-GHR-25-00003',
        creationDate: '2025-01-25T09:45:00.000Z',
        releaseDate: '2025-02-20T00:00:00.000Z',
        duration: 234,
        thumbnail: 'https://picsum.photos/seed/track003/300/300',
        artists: [
            {
                id: 'artist_003',
                name: 'Mira Solis',
                role: 'main',
                artistId: 'artist_003',
                thumbnail: 'https://picsum.photos/seed/artist003/300/300',
                createdAt: new Date('2025-01-25T09:45:00.000Z'),
            },
        ],
        plays: 305,
        isSensitiveContent: false,
        file: new File([], 'sunset_lullaby.mp3'),
        fileName: 'sunset_lullaby.mp3',
        songInfo: {
            duration: 234,
            peakData: Array(234)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_004',
        title: 'Night Drive',
        trackId: 'rel_004',
        trackName: 'Night Drive',
        genres: GENRES.COUNTRY,
        labelName: 'Pulse Audio',
        isrc: 'US-PLA-25-00004',
        creationDate: '2025-01-10T14:00:00.000Z',
        releaseDate: '2025-01-20T00:00:00.000Z',
        duration: 180,
        thumbnail: 'https://picsum.photos/seed/track004/300/300',
        artists: [
            {
                id: 'artist_004',
                name: 'DJ Nova',
                role: 'main',
                artistId: 'artist_004',
                thumbnail: 'https://picsum.photos/seed/artist004/300/300',
                createdAt: new Date('2025-01-10T14:00:00.000Z'),
            },
        ],
        plays: 2140,
        isSensitiveContent: false,
        file: new File([], 'night_drive.mp3'),
        fileName: 'night_drive.mp3',
        songInfo: {
            duration: 180,
            peakData: Array(180)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_005',
        title: 'Faded Skies',
        trackId: 'rel_005',
        trackName: 'Faded Skies',
        genres: GENRES.ELECTRONIC,
        labelName: 'Dream Records',
        isrc: 'US-DRM-25-00005',
        creationDate: '2024-12-10T11:00:00.000Z',
        releaseDate: '2025-01-05T00:00:00.000Z',
        duration: 245,
        thumbnail: 'https://picsum.photos/seed/track005/300/300',
        artists: [
            {
                id: 'artist_005',
                name: 'Ava Leigh',
                role: 'main',
                artistId: 'artist_005',
                thumbnail: 'https://picsum.photos/seed/artist005/300/300',
                createdAt: new Date('2024-12-10T11:00:00.000Z'),
            },
        ],
        plays: 634,
        isSensitiveContent: false,
        file: new File([], 'faded_skies.mp3'),
        fileName: 'faded_skies.mp3',
        songInfo: {
            duration: 245,
            peakData: Array(245)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_006',
        title: 'Afterglow',
        trackId: 'rel_006',
        trackName: 'Afterglow',
        genres: GENRES.ROCK,
        labelName: 'Neon Waves',
        isrc: 'US-NEO-25-00006',
        creationDate: '2024-11-15T15:30:00.000Z',
        releaseDate: '2024-12-01T00:00:00.000Z',
        duration: 260,
        thumbnail: 'https://picsum.photos/seed/track006/300/300',
        artists: [
            {
                id: 'artist_006',
                name: 'Elio Gray',
                role: 'main',
                artistId: 'artist_006',
                thumbnail: 'https://picsum.photos/seed/artist006/300/300',
                createdAt: new Date('2024-11-15T15:30:00.000Z'),
            },
        ],
        plays: 842,
        isSensitiveContent: false,
        file: new File([], 'afterglow.mp3'),
        fileName: 'afterglow.mp3',
        songInfo: {
            duration: 260,
            peakData: Array(260)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_007',
        title: 'Crimson Hearts',
        trackId: 'rel_007',
        trackName: 'Crimson Hearts',
        genres: GENRES.REGGAE,
        labelName: 'Velvet Sound',
        isrc: 'US-VEL-25-00007',
        creationDate: '2025-04-01T12:00:00.000Z',
        releaseDate: '2025-04-10T00:00:00.000Z',
        duration: 200,
        thumbnail: 'https://picsum.photos/seed/track007/300/300',
        artists: [
            {
                id: 'artist_007',
                name: 'Aiden Cole',
                role: 'main',
                artistId: 'artist_007',
                thumbnail: 'https://picsum.photos/seed/artist007/300/300',
                createdAt: new Date('2025-04-01T12:00:00.000Z'),
            },
        ],
        plays: 455,
        isSensitiveContent: false,
        file: new File([], 'crimson_hearts.mp3'),
        fileName: 'crimson_hearts.mp3',
        songInfo: {
            duration: 200,
            peakData: Array(200)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_008',
        title: 'Binary Love',
        trackId: 'rel_008',
        trackName: 'Binary Love',
        genres: GENRES.POP,
        labelName: 'Digital Flame',
        isrc: 'US-DGF-25-00008',
        creationDate: '2025-03-12T13:15:00.000Z',
        releaseDate: '2025-03-28T00:00:00.000Z',
        duration: 222,
        thumbnail: 'https://picsum.photos/seed/track008/300/300',
        artists: [
            {
                id: 'artist_008',
                name: 'Kira Blaze',
                role: 'main',
                artistId: 'artist_008',
                thumbnail: 'https://picsum.photos/seed/artist008/300/300',
                createdAt: new Date('2025-03-12T13:15:00.000Z'),
            },
        ],
        plays: 1290,
        isSensitiveContent: false,
        file: new File([], 'binary_love.mp3'),
        fileName: 'binary_love.mp3',
        songInfo: {
            duration: 222,
            peakData: Array(222)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_009',
        title: 'Waves of You',
        trackId: 'rel_009',
        trackName: 'Waves of You',
        genres: GENRES.BLUES,
        labelName: 'Oceanic Notes',
        isrc: 'US-OCN-25-00009',
        creationDate: '2025-02-20T16:00:00.000Z',
        releaseDate: '2025-03-01T00:00:00.000Z',
        duration: 250,
        thumbnail: 'https://picsum.photos/seed/track009/300/300',
        artists: [
            {
                id: 'artist_009',
                name: 'Janet Echo',
                role: 'main',
                artistId: 'artist_009',
                thumbnail: 'https://picsum.photos/seed/artist009/300/300',
                createdAt: new Date('2025-02-20T16:00:00.000Z'),
            },
        ],
        plays: 712,
        isSensitiveContent: false,
        file: new File([], 'waves_of_you.mp3'),
        fileName: 'waves_of_you.mp3',
        songInfo: {
            duration: 250,
            peakData: Array(250)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_010',
        title: 'Reflections',
        trackId: 'rel_010',
        trackName: 'Reflections',
        genres: GENRES.HIP_HOP,
        labelName: 'Mindscape Studios',
        isrc: 'US-MNS-25-00010',
        creationDate: '2025-01-05T10:30:00.000Z',
        releaseDate: '2025-01-25T00:00:00.000Z',
        duration: 278,
        thumbnail: 'https://picsum.photos/seed/track010/300/300',
        artists: [
            {
                id: 'artist_010',
                name: 'Talia Wynn',
                role: 'main',
                artistId: 'artist_010',
                thumbnail: 'https://picsum.photos/seed/artist010/300/300',
                createdAt: new Date('2025-01-05T10:30:00.000Z'),
            },
        ],
        plays: 1580,
        isSensitiveContent: false,
        file: new File([], 'reflections.mp3'),
        fileName: 'reflections.mp3',
        songInfo: {
            duration: 278,
            peakData: Array(278)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_009',
        title: 'Waves of You',
        trackId: 'rel_009',
        trackName: 'Waves of You',
        genres: GENRES.BLUES,
        labelName: 'Oceanic Notes',
        isrc: 'US-OCN-25-00009',
        creationDate: '2025-02-20T16:00:00.000Z',
        releaseDate: '2025-03-01T00:00:00.000Z',
        duration: 250,
        thumbnail: 'https://picsum.photos/seed/track009/300/300',
        artists: [
            {
                id: 'artist_009',
                name: 'Janet Echo',
                role: 'main',
                artistId: 'artist_009',
                thumbnail: 'https://picsum.photos/seed/artist009/300/300',
                createdAt: new Date('2025-02-20T16:00:00.000Z'),
            },
        ],
        plays: 712,
        isSensitiveContent: false,
        file: new File([], 'waves_of_you.mp3'),
        fileName: 'waves_of_you.mp3',
        songInfo: {
            duration: 250,
            peakData: Array(250)
                .fill(0)
                .map(() => Math.random()),
        },
    },
    {
        id: 'track_010',
        title: 'Reflections',
        trackId: 'rel_010',
        trackName: 'Reflections',
        genres: GENRES.HIP_HOP,
        labelName: 'Mindscape Studios',
        isrc: 'US-MNS-25-00010',
        creationDate: '2025-01-05T10:30:00.000Z',
        releaseDate: '2025-01-25T00:00:00.000Z',
        duration: 278,
        thumbnail: 'https://picsum.photos/seed/track010/300/300',
        artists: [
            {
                id: 'artist_010',
                name: 'Talia Wynn',
                role: 'main',
                artistId: 'artist_010',
                thumbnail: 'https://picsum.photos/seed/artist010/300/300',
                createdAt: new Date('2025-01-05T10:30:00.000Z'),
            },
        ],
        plays: 1580,
        isSensitiveContent: false,
        file: new File([], 'reflections.mp3'),
        fileName: 'reflections.mp3',
        songInfo: {
            duration: 278,
            peakData: Array(278)
                .fill(0)
                .map(() => Math.random()),
        },
    },
];
