export const PERMISSION = {
    DASHBOARD: {
        READ: 'dashboard.read',
    },
    ARTIST: {
        CREATE: 'artist.create',
        DELETE: 'artist.delete',
        LINK_LABEL: 'artist.link_label',
        MANAGE_MEMBERS: 'artist.manage_members',
        MANAGE_PAYOUTS: 'artist.manage_payouts',
        MANAGE_SOCIAL: 'artist.manage_social',
        READ: 'artist.read',
        UPDATE: 'artist.update',
        VERIFY: 'artist.verify',
    },
    DSP: {
        CONFIGURE_INTEGRATION: 'dsp.configure_integration',
        CREATE: 'dsp.create',
        DELETE: 'dsp.delete',
        DISABLE: 'dsp.disable',
        ENABLE: 'dsp.enable',
        FETCH_REPORTS: 'dsp.fetch_reports',
        READ: 'dsp.read',
        RETRY_DELIVERY: 'dsp.retry_delivery',
        SYNC_CATALOG: 'dsp.sync_catalog',
        UPDATE: 'dsp.update',
        VIEW_DELIVERY: 'dsp.view_delivery',
    },
    GENRE: {
        ASSIGN: 'genre.assign',
        CREATE: 'genre.create',
        DELETE: 'genre.delete',
        READ: 'genre.read',
        UPDATE: 'genre.update',
    },
    LABEL: {
        CREATE: 'label.create',
        DELETE: 'label.delete',
        MANAGE_CONTRACTS: 'label.manage_contracts',
        MANAGE_MEMBERS: 'label.manage_members',
        MANAGE_PAYOUTS: 'label.manage_payouts',
        READ: 'label.read',
        UPDATE: 'label.update',
        VERIFY: 'label.verify',
    },
    RELEASE: {
        APPROVE: 'release.approve',
        CREATE: 'release.create',
        DELETE: 'release.delete',
        MANAGE_RIGHTS: 'release.manage_rights',
        PUBLISH: 'release.publish',
        READ: 'release.read',
        REJECT: 'release.reject',
        SCHEDULE: 'release.schedule',
        SUBMIT_DSP: 'release.submit_dsp',
        UNPUBLISH: 'release.unpublish',
        UPDATE: 'release.update',
        VIEW_HISTORY: 'release.view_history',
        VIEW_STATUS: 'release.view_status',
    },
    TRACK: {
        APPROVE: 'track.approve',
        ATTACH_TO_RELEASE: 'track.attach_to_release',
        CREATE: 'track.create',
        DELETE: 'track.delete',
        MANAGE_AUDIO: 'track.manage_audio',
        MANAGE_ISRC: 'track.manage_isrc',
        MANAGE_LYRICS: 'track.manage_lyrics',
        READ: 'track.read',
        REJECT: 'track.reject',
        UPDATE: 'track.update',
    },
} as const;
