import { QUERY_KEY } from '@/constants/query-key';
import { COLUMN_PRODUCT_DISPLAY } from '../enums';

export const productQueryKeys = {
    all: [QUERY_KEY.PRODUCT.KEY],
    getList: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_PRODUCT_LIST],
    getCountType: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_COUNT_TYPE],
    getCountStatus: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_COUNT_STATUS],
    getCountTopic: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_COUNT_TOPIC],
    getCountAssignee: [
        QUERY_KEY.PRODUCT.KEY,
        QUERY_KEY.PRODUCT.GET_COUNT_ASSIGNEE,
    ],
    getCountCreator: [
        QUERY_KEY.PRODUCT.KEY,
        QUERY_KEY.PRODUCT.GET_COUNT_CREATOR,
    ],
    getStatistic: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_PRODUCT_LIST],
    getDetail: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_PRODUCT_DETAIL],
    getAssigneeUserList: [QUERY_KEY.PRODUCT.KEY, QUERY_KEY.PRODUCT.GET_CREATOR],
    getApprovalUserList: [
        QUERY_KEY.PRODUCT.KEY,
        QUERY_KEY.PRODUCT.GET_APPROVER,
    ],
};

export const defaultVisibleColumnsProduct: COLUMN_PRODUCT_DISPLAY[] = [
    COLUMN_PRODUCT_DISPLAY.PRODUCT,
    COLUMN_PRODUCT_DISPLAY.CODE,
    COLUMN_PRODUCT_DISPLAY.CREATOR,
    COLUMN_PRODUCT_DISPLAY.ASSIGNEE,
    COLUMN_PRODUCT_DISPLAY.APPROVER,
    // COLUMN_PRODUCT_DISPLAY.CONTENT,
    // COLUMN_PRODUCT_DISPLAY.DESCRIPTION,
    COLUMN_PRODUCT_DISPLAY.RATE,
    COLUMN_PRODUCT_DISPLAY.TYPE,
    COLUMN_PRODUCT_DISPLAY.STATUS,
    COLUMN_PRODUCT_DISPLAY.DATE_CREATED,
    COLUMN_PRODUCT_DISPLAY.DEADLINE,
    COLUMN_PRODUCT_DISPLAY.ACTION,
    COLUMN_PRODUCT_DISPLAY.PRIORITY,
];
