export const fieldLabels: Record<string, string> = {
    type: 'Loại phát hành',
    nameRelease: 'Tên phát hành',
    version: 'Phiên bản',
    isMoreThan4Artists: 'Có nhiều hơn 4 nghệ sĩ hay không',
    artists: 'Nghệ sĩ',
    subArtists: 'Nghệ sĩ phụ',
    genres: 'Thể loại',
    subGenres: 'Thể loại phụ',
    language: 'Ngôn ngữ',
    label: 'Label',
    upc: 'UPC/EAN/JAN',
    catalogId: 'ID category',
    cLineYear: 'C line year',
    pLineYear: 'P line year',
    thumbnail: 'Thumbnail',
    tracks: 'Bài hát',
    title: 'Tên bài hát',
    isrc: 'ISRC',
    mainArtist: 'Nghệ sĩ chính',
    originalSource: 'Nguồn gốc',
    languageTrack: 'Ngôn ngữ',
    genresTrack: 'Thể loại',
    subGenresTrack: 'Thể loại phụ',
    sensitiveContent: 'Nội dung nhạy cảm',
    countryLanguage: 'Quốc gia',
    MetadataLanguage: 'Ngôn ngữ',
    lyrics: 'Lời bài hát',
    audioSpecifications: 'Thông số kỹ thuật',
    format: 'Định dạng',
    codec: 'Codec',
    bitrate: 'Bitrate',
    sampleRate: 'Tốc độ lấy mẫu',
    channel: 'Kênh',
    publishing: 'Xuất bản',
    publisher: 'Nhà xuất bản',
    publishingDate: 'Ngày xuất bản',
    publishingType: 'Loại xuất bản',
    role: 'Vai trò',
    musicianName: 'Tên nhạc sĩ',
    percent: 'Phần trăm',
};
