import { RELEASES_COLUMNS_DISPLAY } from '../enums';

export const defaultVisibleColumnsReleases = [
    // RELEASES_COLUMNS_DISPLAY.I_NO,
    RELEASES_COLUMNS_DISPLAY.THUMBNAIL,
    RELEASES_COLUMNS_DISPLAY.TITLE,
    RELEASES_COLUMNS_DISPLAY.ARTIST,
    RELEASES_COLUMNS_DISPLAY.PUBLISHER,
    // RELEASES_COLUMNS_DISPLAY.RELEASE_ID,
    RELEASES_COLUMNS_DISPLAY.TYPE,
    // RELEASES_COLUMNS_DISPLAY.UPC,
    RELEASES_COLUMNS_DISPLAY.STATUS,
    RELEASES_COLUMNS_DISPLAY.TRACK_COUNT,
    // RELEASES_COLUMNS_DISPLAY.DURATION,
    RELEASES_COLUMNS_DISPLAY.RELEASE_DATE,
    // RELEASES_COLUMNS_DISPLAY.CREATION_DATE,
    RELEASES_COLUMNS_DISPLAY.ACTIONS,
];
