export enum TYPE_MODAL_TOPIC {
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    UPLOAD = 'UPLOAD',
    DELETE = 'DELETE',
    DETAIL = 'DETAIL',
}

export enum TOPIC_TYPE_FILTER {
    DROPDOWN = 'DROPDOWN',
    KEYWORD = 'KEYWORD',
    IS_ACTIVE = 'IS_ACTIVE',
}
