import { CountriesData } from './types';

export const fakeCountriesData: CountriesData[] = [
    {
        id: '1',
        name: 'Việt Nam',
        iso3: 'VNM',
        iso2: 'VN',
        numericCode: '704',
        phoneCode: '+84',
        capital: 'Hà Nội',
        currency: 'VND',
        currencyName: 'Vietnamese dong',
        currencySymbol: '₫',
        nationality: 'Vietnamese',
        createdAt: '2023-01-15T10:20:30Z',
        updatedAt: '2023-01-15T10:20:30Z',
        regionId: 0,
    },
    {
        id: '2',
        name: 'United States',
        iso3: 'USA',
        iso2: 'US',
        numericCode: '840',
        phoneCode: '+1',
        capital: 'Washington, D.C.',
        currency: 'USD',
        currencyName: 'US Dollar',
        currencySymbol: '$',
        nationality: 'American',
        createdAt: '2023-01-15T10:20:30Z',
        updatedAt: '2023-01-15T10:20:30Z',
        regionId: 0,
    },
];
