export enum TYPE_MODAL_AGGREGATOR {
    CREATE = 'CREATE_AGGREGATOR',
    UPDATE = 'UPDATE_AGGREGATOR',
    DELETE = 'DELETE_AGGREGATOR',
    DETAIL = 'DETAIL_AGGREGATOR',
}

export enum DISTRIBUTION_CHANNEL_PROTOCOL {
    FTP = 'FTP',
    SFTP = 'SFTP',
    API = 'API',
}

export enum ERN_VERSION {
    ERN_43 = '4.3',
    ERN_382 = '3.8.2',
}
