export enum TYPE_MODAL_RELEASE_VIDEO {
    CREATE = 'CREATE_RELEASE_VIDEO',
    UPDATE = 'UPDATE_RELEASE_VIDEO',
    DELETE = 'DELETE_RELEASE_VIDEO',
}

export enum RELEASE_VIDEO_TABS {
    DETAILS = 'details',
    ADDITIONAL = 'additional',
    DISTRIBUTION = 'distribution',
    SUBMITS = 'submits',
}

export enum RELEASE_VIDEO_VISIBILITY {
    DEFAULT = 'DEFAULT',
    UNLISTED_ON_YOUTUBE = 'UNLISTED_ON_YOUTUBE',
    UNLISTED_ON_VEVO = 'UNLISTED_ON_VEVO',
    UNLISTED_ON_YOUTUBE_VEVO = 'UNLISTED_ON_YOUTUBE_VEVO',
}

export enum RELEASE_VIDEO_CAPTION_TYPE {
    CAPTION = 'CAPTION',
    SUBTITLE = 'SUBTITLE',
}
