export enum RELEASE_EXECUTION_TYPE {
    INITIAL_RELEASE = 'INITIAL_RELEASE',
    UPDATE = 'UPDATE',
    TAKEDOWN = 'TAKEDOWN',
    RETRY = 'RETRY',
}

export enum RELEASE_EXECUTION_STATUS {
    QUEUED = 'QUEUED',
    RUNNING = 'RUNNING',
    AWAITING_ACTION = 'AWAITING_ACTION',
    COMPLETED = 'COMPLETED',
    PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
}

export enum TYPE_MODAL_RELEASE_EXECUTION {
    DETAIL = 'DETAIL_RELEASE_EXECUTION',
}

export enum STEP_TYPE {
    VALIDATE = 'VALIDATE',
    GEN_UPC_ISRC = 'GEN_UPC_ISRC',
    CREATE_METADATA = 'CREATE_METADATA',
    UPLOAD_SFTP = 'UPLOAD_SFTP',
    POST_UPLOAD_HOOK = 'POST_UPLOAD_HOOK',
    EXPORT_EXCEL = 'EXPORT_EXCEL',
    SEND_EMAIL = 'SEND_EMAIL',
    WAITING_EXPORT = 'WAITING_EXPORT',
    CLEANUP = 'CLEANUP',
}

export enum STEP_STATUS {
    PENDING = 'PENDING',
    RUNNING = 'RUNNING',
    SUCCESS = 'SUCCESS',
    FAILED = 'FAILED',
    SKIPPED = 'SKIPPED',
    WAITING_ACTION = 'WAITING_ACTION',
    CANCELLED = 'CANCELLED',
}
