import { QUERY_KEY } from '@/constants/query-key';
import { COLUMN_ORDER_DISPLAY } from '../enums';

export const orderQueryKeys = {
    all: [QUERY_KEY.ORDER.KEY],
    getList: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_ORDER_LIST],
    getCountType: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_COUNT_TYPE],
    getCountStatus: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_COUNT_STATUS],
    getCountUseStatus: [
        QUERY_KEY.ORDER.KEY,
        QUERY_KEY.ORDER.GET_COUNT_USE_STATUS,
    ],
    getCountCreator: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_COUNT_CREATOR],
    getCountAssignee: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_COUNT_ASSIGNEE],
    getStatistic: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_ORDER_LIST],
    getDetail: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_ORDER_DETAIL],
    getCreatorUserList: [QUERY_KEY.ORDER.KEY, QUERY_KEY.ORDER.GET_CREATOR],
};

export const commentRatingQueryKeys = {
    all: [QUERY_KEY.COMMENT_RATING.KEY],
    getList: [
        QUERY_KEY.COMMENT_RATING.KEY,
        QUERY_KEY.COMMENT_RATING.GET_COMMENT_RATING_LIST,
    ],
    getDetail: [
        QUERY_KEY.COMMENT_RATING.KEY,
        QUERY_KEY.COMMENT_RATING.GET_COMMENT_RATING_DETAIL,
    ],
};

export const defaultVisibleColumns: COLUMN_ORDER_DISPLAY[] = [
    COLUMN_ORDER_DISPLAY.Product,
    COLUMN_ORDER_DISPLAY.Code,
    COLUMN_ORDER_DISPLAY.Creator,
    COLUMN_ORDER_DISPLAY.Assignee,
    // COLUMN_ORDER_DISPLAY.Content,
    COLUMN_ORDER_DISPLAY.Status,
    // COLUMN_ORDER_DISPLAY.UsedStatus,
    COLUMN_ORDER_DISPLAY.OrderType,
    COLUMN_ORDER_DISPLAY.DateCreated,
    COLUMN_ORDER_DISPLAY.Deadline,
    COLUMN_ORDER_DISPLAY.Action,
    COLUMN_ORDER_DISPLAY.Priority,
];
