import { QUERY_KEY } from '@/constants/query-key';

export const topicQueryKeys = {
    all: [QUERY_KEY.TOPIC.KEY],
    getList: [QUERY_KEY.TOPIC.KEY, QUERY_KEY.TOPIC.GET_TOPIC_LIST],
    getTopicAssignee: [QUERY_KEY.TOPIC.KEY, QUERY_KEY.TOPIC.GET_TOPIC_ASSIGNEE],
    getTopicCount: [QUERY_KEY.TOPIC.KEY, QUERY_KEY.TOPIC.GET_TOPIC_COUNT],
    getActiveCount: [QUERY_KEY.TOPIC.KEY, QUERY_KEY.TOPIC.GET_ACTIVE_COUNT],
    getListAll: [QUERY_KEY.TOPIC.KEY, QUERY_KEY.TOPIC.GET_TOPIC_LIST_ALL],
    getDetail: [QUERY_KEY.TOPIC.KEY, QUERY_KEY.TOPIC.GET_TOPIC_DETAIL],
};
