export enum RELEASE_SUBMIT_TYPE {
    INITIAL_RELEASE = 'INITIAL_RELEASE',
    UPDATE = 'UPDATE',
    TAKEDOWN = 'TAKEDOWN',
    RETRY = 'RETRY',
}

export enum RELEASE_SUBMIT_STEP_TYPE {
    GEN_UPC = 'GEN_UPC',
    GEN_ISRCS = 'GEN_ISRCS',
    GEN_ISRC = 'GEN_ISRC',
    VALIDATE = 'VALIDATE',
}

export enum RELEASE_EXECUTION_STEP_TYPE {
    GEN_UPC = 'GEN_UPC',
    GEN_ISRCS = 'GEN_ISRCS',
    GEN_ISRC = 'GEN_ISRC',
    VALIDATE = 'VALIDATE',
    PROCESS_DSPS = 'PROCESS_DSPS',
    PROCESS_DIRECT = 'PROCESS_DIRECT',
    PROCESS_DIRECT_CHILD = 'PROCESS_DIRECT_CHILD',
    SYNC_DATA_PARTNER = 'SYNC_DATA_PARTNER',
    PROCESS_AGG = 'PROCESS_AGG',
    PROCESS_AGG_CI = 'PROCESS_AGG_CI',
    IMPORT_CI = 'IMPORT_CI',
    EXPORT_CI = 'EXPORT_CI',
    CREATE_FOLDER_DONE_CI = 'CREATE_FOLDER_DONE_CI',
    VALIDATE_QA_CI = 'VALIDATE_QA_CI',
    EXPORT_AGG_CI_CI = 'EXPORT_CI_CI',
    EXPORT_AGG_CI_STATE51 = 'EXPORT_AGG_CI_STATE51',
    WAITING_ADMIN_EXPORT = 'WAITING_ADMIN_EXPORT',
    SEND_EMAIL_STATE51 = 'SEND_EMAIL_STATE51',
    SYNC_DATA_DSP_CI = 'SYNC_DATA_DSP_CI',
    WAIT_PARTNER_PROCESS = 'WAIT_PARTNER_PROCESS',
    CREATE_METADATA_ON_SERVER = 'CREATE_METADATA_ON_SERVER',
    UPLOAD_METADATA_TO_SFTP = 'UPLOAD_METADATA_TO_SFTP',
    SYNC_RESULT_TO_RELEASE = 'SYNC_RESULT_TO_RELEASE',
    SUBMIT_VEVO_VIDEO = 'SUBMIT_VEVO_VIDEO',
}

export enum RELEASE_SUBMIT_STATUS {
    NEW = 'NEW',
    PROCESSING = 'PROCESSING',
    WAITING_ACTION = 'WAITING_ACTION',
    WAITING_PARTNER = 'WAITING_PARTNER',
    DONE = 'DONE',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
    // PARTIAL_DONE = 'PARTIAL_DONE',
}

export enum RELEASE_SUBMIT_STEP_STATUS {
    PENDING = 'PENDING',
    RUNNING = 'RUNNING',
    SUCCESS = 'SUCCESS',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
    NEW = 'NEW',
    DONE = 'DONE',
    PROCESSING = 'PROCESSING',
    WAITING_ACTION = 'WAITING_ACTION',
}

export enum RELEASE_PARENT_GROUP_STEPS {
    PROCESS_DIRECT = 'PROCESS_DIRECT',
    PROCESS_AGG_CI = 'PROCESS_AGG_CI',
}

export enum DIRECT_DSP_SUB_STEPS {
    CREATE_METADATA_DIRECT = 'CREATE_METADATA_DIRECT',
    UPLOAD_SFTP_DIRECT = 'UPLOAD_SFTP_DIRECT',
    SYNC_DATA_FROM_DSP = 'SYNC_DATA_FROM_DSP',
}

export enum CI_AGGREGATOR_SUB_STEP {
    CREATE_METADATA_CI = 'CREATE_METADATA_CI',
    UPLOAD_SFTP_CI = 'UPLOAD_SFTP_CI',
    CREATE_FOLDER_DONE_CI = 'CREATE_FOLDER_DONE_CI',
    GET_QA_FLAG_CI = 'GET_QA_FLAG_CI',
    SEND_EMAIL_TO_STATE = 'SEND_EMAIL_TO_STATE',
    WAITING_ADMIN_EXPORT = 'WAITING_ADMIN_EXPORT',
    SYNC_DATA_DSP_CI = 'SYNC_DATA_DSP_CI',
}

export enum RELEASE_SUBMIT_LOG_LEVEL {
    SUCCESS = 'SUCCESS',
    LOG = 'LOG',
    ERROR = 'ERROR',
    WARNING = 'WARNING',
}

export enum CHILD_EXECUTION_MODE {
    SEQUENTIAL = 'sequential',
    PARALLEL = 'parallel',
}

export enum RELEASE_SUBMIT_SORT_FIELD {
    CREATED_AT = 'execution.createdAt',
    TYPE = 'execution.type',
    RELEASE_TITLE = 'execution.releaseTitle',
    RELEASE_UPC = 'execution.releaseUpc',
    STATUS = 'execution.status',
}

export enum FieldOrderReleaseExecution3 {
    execution_createdAt = 'execution.createdAt',
    execution_type = 'execution.type',
    execution_releaseTitle = 'execution.releaseTitle',
    execution_releaseUpc = 'execution.releaseUpc',
    execution_status = 'execution.status',
}
