export enum RELEASE_SUBMIT_STEP_TYPE {
    GEN_UPC = 'GEN_UPC',
    GEN_ISRCS = 'GEN_ISRCS',
    GEN_ISRC = 'GEN_ISRC',
    VALIDATE = 'VALIDATE',
}

export enum RELEASE_SUBMIT_STATUS {
    NEW = 'NEW',
    PROCESSING = 'PROCESSING',
    WAITING_ACTION = 'WAITING_ACTION',
    DONE = 'DONE',
    FAILED = 'FAILED',
    PARTIAL_DONE = 'PARTIAL_DONE',
}

export enum RELEASE_SUBMIT_STEP_STATUS {
    PENDING = 'PENDING',
    RUNNING = 'RUNNING',
    SUCCESS = 'SUCCESS',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
    NEW = 'NEW',
    DONE = 'DONE',
    PROCESSING = 'PROCESSING',
    WAITING_ACTION = 'WAITING_ACTION',
}

export enum RELEASE_PARENT_GROUP_STEPS {
    PROCESS_DIRECT = 'PROCESS_DIRECT',
    PROCESS_AGG_CI = 'PROCESS_AGG_CI',
}

export enum DIRECT_DSP_SUB_STEPS {
    CREATE_METADATA_DIRECT = 'CREATE_METADATA_DIRECT',
    UPLOAD_SFTP_DIRECT = 'UPLOAD_SFTP_DIRECT',
    SYNC_DATA_FROM_DSP = 'SYNC_DATA_FROM_DSP',
}

export enum CI_AGGREGATOR_SUB_STEP {
    CREATE_METADATA_CI = 'CREATE_METADATA_CI',
    UPLOAD_SFTP_CI = 'UPLOAD_SFTP_CI',
    CREATE_FOLDER_DONE_CI = 'CREATE_FOLDER_DONE_CI',
    GET_QA_FLAG_CI = 'GET_QA_FLAG_CI',
    SEND_EMAIL_TO_STATE = 'SEND_EMAIL_TO_STATE',
    WAITING_ADMIN_EXPORT = 'WAITING_ADMIN_EXPORT',
    SYNC_DATA_DSP_CI = 'SYNC_DATA_DSP_CI',
}

export enum RELEASE_SUBMIT_LOG_LEVEL {
    SUCCESS = 'SUCCESS',
    LOG = 'LOG',
    ERROR = 'ERROR',
    WARNING = 'WARNING',
}
